export const PROJECTS = [
  {
    id: "1",
    title: "Predictive House Pricing Model",
    description: "Machine learning model to predict house prices using regression algorithms and feature engineering.",
    category: "ml",
    technologies: ["Python", "Scikit-learn", "Pandas"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com",
    gradient: "bg-gradient-to-br from-primary to-accent",
  },
  {
    id: "2", 
    title: "COVID-19 Data Dashboard",
    description: "Interactive dashboard visualizing COVID-19 trends with real-time data and geographical mapping.",
    category: "viz",
    technologies: ["Plotly", "Dash", "Python"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com",
    gradient: "bg-gradient-to-br from-green-500 to-blue-500",
  },
  {
    id: "3",
    title: "Sentiment Analysis Engine", 
    description: "Natural Language Processing model to analyze sentiment in social media posts and reviews.",
    category: "ai",
    technologies: ["NLTK", "Transformers", "PyTorch"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com",
    gradient: "bg-gradient-to-br from-purple-500 to-pink-500",
  },
  {
    id: "4",
    title: "E-commerce Sales Analysis",
    description: "Comprehensive analysis of e-commerce sales data with customer segmentation and insights.",
    category: "analysis", 
    technologies: ["Pandas", "Seaborn", "Jupyter"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com",
    gradient: "bg-gradient-to-br from-yellow-500 to-red-500",
  },
  {
    id: "5",
    title: "Image Classification CNN",
    description: "Deep learning model for image classification using Convolutional Neural Networks.",
    category: "ml",
    technologies: ["TensorFlow", "Keras", "OpenCV"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com", 
    gradient: "bg-gradient-to-br from-indigo-500 to-purple-600",
  },
  {
    id: "6",
    title: "Stock Market Tracker",
    description: "Real-time stock market visualization with technical indicators and portfolio tracking.",
    category: "viz",
    technologies: ["React", "D3.js", "API"],
    githubUrl: "https://github.com",
    liveUrl: "https://example.com",
    gradient: "bg-gradient-to-br from-teal-500 to-cyan-500",
  },
];

export const TYPING_PHRASES = [
  "Machine Learning",
  "Data Analytics", 
  "Artificial Intelligence",
  "Deep Learning",
  "Data Visualization"
];
